# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date created')),
                ('text', models.CharField(max_length=250, verbose_name='Name the comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Article')),
                ('text', models.TextField(max_length=250, verbose_name='Full description')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
